[package]
name = "alsa-test"
version = "0.1.0"
edition = "2024"

[dependencies]
alsa = "0.9.1"
futures = "0.3.31"
libc = "0.2.172"
pin-project = "1.1.10"
tokio = { version = "1.47.1", features = ["full", "io-std", "io-util", "macros", "rt"] }
